### ISSUE TITLE
Add a flag to force use `node-fetch`

### ISSUE THREAD

**Issue by pi0** [unjs/node-fetch-native#56]
### Describe the feature

https://github.com/nuxt/nuxt/issues/19245

Since Node.js native fetch can be unstable sometimes, instead of downgrading Node.js as workaround, we shall introduce an environment variable to force uses `node-fetch` for Node.js environemnts

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by rudimediaz** [comment]
i am just curious. is this related to the issue?

> 2023-02-24T14:42:11.834013Z	file:///opt/buildhome/repo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432
2023-02-24T14:42:11.834354Z			            throw new TypeError(`${context} is not a ReadableStream.`);
2023-02-24T14:42:11.834519Z			                  ^
2023-02-24T14:42:11.834643Z	
2023-02-24T14:42:11.834802Z	TypeError: First parameter has member 'readable' that is not a ReadableStream.
2023-02-24T14:42:11.834921Z	    at assertReadableStream (file:///opt/buildhome/repo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432:21)
2023-02-24T14:42:11.835033Z	    at convertReadableWritablePair (file:///opt/buildhome/repo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3509:11)
2023-02-24T14:42:11.835149Z	    at ReadableStream.pipeThrough (file:///opt/buildhome/repo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3584:33)
2023-02-24T14:42:11.835259Z	    at fetchFinale (/opt/buildhome/repo/node_modules/undici/lib/fetch/index.js:973:52)
2023-02-24T14:42:11.835394Z	    at mainFetch (/opt/buildhome/repo/node_modules/undici/lib/fetch/index.js:773:5)
2023-02-24T14:42:11.835504Z	    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-02-24T14:42:11.853036Z	Failed: build command exited with code: 1
2023-02-24T14:42:12.653682Z	Failed: an internal error occurred

I got this error log from my site deployments(an astro site on cloudflare pages w/ node v 16.13 as NODE_VERSION env variable).  I checked npm list and unocss-preset-icons depends on this package.
