### ISSUE TITLE
How to make it work on less than node v18.0.0

### ISSUE THREAD

**Issue by huabin** [unjs/node-fetch-native#60]
### Environment

node version: v17.9.1

### Reproduction

- Install node version v17.9.1
- run the project via `npm run dev`
- get the error

### Describe the bug

If using the node  is under version 18.0.0, I will get the error

```
file:///Users/Dev/node/skom/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432
		            throw new TypeError(`${context} is not a ReadableStream.`);
		                  ^

TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (file:///Users/Dev/node/skom/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432:21)
    at convertReadableWritablePair (file:///Users/Dev/node/skom/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3509:11)
    at ReadableStream.pipeThrough (file:///Users/Dev/node/skom/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3584:33)
    at fetchFinale (/Users/Dev/node/skom/node_modules/undici/lib/fetch/index.js:973:52)
    at mainFetch (/Users/Dev/node/skom/node_modules/undici/lib/fetch/index.js:773:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by huabin** [comment]
fixed.
