### ISSUE TITLE
react-native: `node:http` could not be found

### ISSUE THREAD

**Issue by homersimpsons** [unjs/node-fetch-native#91]
### Environment

- react-native: 0.71.0
- ofetch: 1.1.0

### Reproduction

1. Start a react-native project
2. `yarn add ofetch@1.1.0`
3. Add a request: `ofetch('www.example.com')`
4. Notice the bug

### Describe the bug

I just tried this on `react-native` (after unjs/ofetch#206) and it looks like it does not work because of `node:http`:

> node:http could not be found within the project or in these directories

![Screenshot (Jun 20, 2023 17 46 46)](https://github.com/unjs/ofetch/assets/16977446/8072a71f-1ef5-4b35-b480-09a93f353c3b)

### Logs

```sh
error: Error: Unable to resolve module node:http from /homer/user/project/node_modules/ofetch/dist/node.cjs: node:http could not be found within the project or in these directories:
  node_modules
  ../../node_modules
  1 | 'use strict';
  2 |
> 3 | const http = require('node:http');
    |                       ^
  4 | const https = require('node:https');
  5 | const nodeFetch = require('node-fetch-native');
  6 | const fetch$1 = require('./shared/ofetch.0fda5c9e.cjs');
    at ModuleResolver.resolveDependency (/homer/user/project/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:162:15)
    at DependencyGraph.resolveDependency (/homer/user/project/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/homer/user/project/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/homer/user/project/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/homer/user/project/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at async Graph._addDependency (/homer/user/project/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 0)
    at async Graph._processModule (/homer/user/project/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._traverseDependenciesForSingleFile (/homer/user/project/node_modules/metro/src/DeltaBundler/Graph.js:207:5)
    at async Graph.traverseDependencies (/homer/user/project/node_modules/metro/src/DeltaBundler/Graph.js:147:9)
```

**Comment by pi0** [comment]
Hi. We recently added support for `reactnartive` export condition in `node-fetch-native` (https://github.com/unjs/node-fetch-native/blob/f6c0996f3dda1ff84c41a868a08798266051523d/package.json#L17) which should fix the issue with ofetch as well as we use this lib.

Let me know if still having issues to reopen and investigate!

**Comment by homersimpsons** [comment]
Looks like the issue still exist with the same stack trace, but maybe this is more in `ofetch` scope:

```
error: Error: Unable to resolve module node:http from /home/user/project/node_modules/ofetch/dist/node.cjs: node:http could not be found within the project or in these directories:
  node_modules/ofetch/node_modules
  node_modules
  ../../node_modules
  1 | 'use strict';
  2 |
> 3 | const http = require('node:http');
    |                       ^
  4 | const https = require('node:https');
  5 | const nodeFetch = require('node-fetch-native');
  6 | const fetch$1 = require('./shared/ofetch.92c14be7.cjs');
    at ModuleResolver.resolveDependency (/home/user/project/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:162:15)
    at DependencyGraph.resolveDependency (/home/user/project/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/home/user/project/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/home/user/project/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/home/user/project/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at async Graph._addDependency (/home/user/project/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 12)
    at async Graph._processModule (/home/user/project/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._addDependency (/home/user/project/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 1)
```

Versions:
- ofetch@1.3.3
- node-fetch-native@1.4.0 (should be `main`  because I installed with `yarn add https://github.com/unjs/node-fetch-native#main`)

**Comment by pi0** [comment]
@homersimpsons It looks like somehow ofetch/node-fetch-native is being imported with wrong export conditions (node) for an unsupported environment.

Feel free to open an issue in higher order respos (Metro, Nuxt, Nitro or ofetch) with a public reproduction so i can check 👍🏼
